-- Create the database
CREATE DATABASE gestion_restaurants;

USE gestion_restaurants;

-- USERS TABLE
CREATE TABLE users (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  id_role INT DEFAULT '3',
  is_archived TINYINT(1) DEFAULT '0',
  is_approved TINYINT(1) DEFAULT '0',
  reset_token VARCHAR(255) DEFAULT NULL,
  reset_token_expiry DATETIME DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (id_role) REFERENCES roles (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ROLES TABLE
CREATE TABLE roles (
  id INT NOT NULL AUTO_INCREMENT,
  role_name VARCHAR(20) DEFAULT 'user',
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- MENU TABLE
CREATE TABLE menu (
  id INT NOT NULL AUTO_INCREMENT,
  id_plat INT DEFAULT NULL,
  id_salade INT DEFAULT NULL,
  id_dessert INT DEFAULT NULL,
  id_user INT DEFAULT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (id_plat) REFERENCES plat (id) ON DELETE CASCADE,
  FOREIGN KEY (id_salade) REFERENCES salade (id) ON DELETE CASCADE,
  FOREIGN KEY (id_dessert) REFERENCES dessert (id) ON DELETE CASCADE,
  FOREIGN KEY (id_user) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- PLAT TABLE
CREATE TABLE plat (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  prix FLOAT NOT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- SALADE TABLE
CREATE TABLE salade (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  prix FLOAT NOT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- DESSERT TABLE
CREATE TABLE dessert (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  prix FLOAT NOT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- COMMANDE TABLE
CREATE TABLE commande (
  id INT NOT NULL AUTO_INCREMENT,
  id_menu INT DEFAULT NULL,
  id_user INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (id_user) REFERENCES users (id) ON DELETE SET NULL,
  FOREIGN KEY (id_menu) REFERENCES menu (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


